language: node_js
os:
  - linux
  - osx
node_js:
  - "0.12"
  - iojs
env:
  - secure: JoSDZUduQrz+WG7WCOYKJTooBoXHF72fHdemFKKm0CJEfaDxr6P75Ihhzp7NTk1nX4VX2qi0FS+7VPSPKU5RB1A5e7EmUKFL8gdL82ExXwwCWR3EH8Y1qv3TdWsfMaEWoaiKzqL7LsewOZaoouyJpSNsu+kKQ+ndzJcKKKmnxh8=
after_success: npm run codeclimate
