// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var bar, foo, func;

  func = function(val1, val2) {
    return console.log(val1 + val2);
  };

  foo = 'hello';

  bar = 'world';

  func(foo, bar);

}).call(this);

//# sourceMappingURL=main.map
